import json
import sys

sys.path.append("src")
from pymafia.kolmafia import km

contents = f"""# THIS FILE IS AUTOMATICALLY GENERATED. See tools/generate_literals.py for more information.
from typing import Literal

BountyNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.BOUNTY_TYPE.allValues().iterator()])}
ClassNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.CLASS_TYPE.allValues().iterator()])}
CoinmasterNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.COINMASTER_TYPE.allValues().iterator()])}
EffectNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.EFFECT_TYPE.allValues().iterator()])}
ElementNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.ELEMENT_TYPE.allValues().iterator()])}
FamiliarNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.FAMILIAR_TYPE.allValues().iterator()])}
ItemNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.ITEM_TYPE.allValues().iterator()])}
LocationNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.LOCATION_TYPE.allValues().iterator()])}
MonsterNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.MONSTER_TYPE.allValues().iterator()])}
PathNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.PATH_TYPE.allValues().iterator()])}
PhylumNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.PHYLUM_TYPE.allValues().iterator()])}
ServantNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.SERVANT_TYPE.allValues().iterator()])}
SkillNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.SKILL_TYPE.allValues().iterator()])}
SlotNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.SLOT_TYPE.allValues().iterator()])}
StatNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.STAT_TYPE.allValues().iterator()])}
ThrallNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.THRALL_TYPE.allValues().iterator()])}
VykeaNames = Literal{json.dumps([x.toJSON() for x in km.DataTypes.VYKEA_TYPE.allValues().iterator()])}
ZodiacNames = Literal{json.dumps([x.getName() for x in km.ZodiacSign.values()])}
"""

with open("src/pymafia/datatypes/literals.py", "w") as f:
    f.write(contents)
