name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      #   - name: Set up Python
      #     uses: actions/setup-python@v5
      #     with:
      #       python-version-file: "pyproject.toml"
      #   - name: Install dependencies
      # run: make install
      - name: Lint
        run: make lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    name: test (Python ${{ matrix.python-version }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin
      - name: Install dependencies
        run: make install
      - name: Test
        run: make test
  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: make install
      - name: Check licenses
        run: make check-licenses
