name: Continuous Integration
on: [push, pull_request]
jobs:
  lint:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name
      != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name
      != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Run mypy
        run: mypy src
      - name: Run tests
        run: poetry run pytest .
