name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install poetry-dynamic-versioning
        run: poetry self add 'poetry-dynamic-versioning[plugin]'
      - name: Install dependencies
        run: poetry install --no-root
      - name: Publish package
        run: |-
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
