name: Update KoLmafia
on:
  workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version-file: .java-version
          distribution: temurin
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
        # TODO Update jar file and minimum version
      - name: Generate ash library
        run: poetry run python scripts/generate_ash_library.py
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        continue-on-error: true
      - name: Rerun pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update KoLmafia from r2700 to r27953'