name: Update KoLmafia
on:
  workflow_dispatch:
    inputs:
      revision:
        description: "KoLmafia revision"
        default: "latest"
        type: string
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Determine revision number
        run: |
          echo "revision_number=$(( 
            ${{ github.event.inputs.revision }} == "latest" 
            ? $(curl https://api.github.com/repos/kolmafia/kolmafia/releases/latest -s | jq .name -r) 
            : ${{ github.event.inputs.revision }}))
          " >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin
      - name: Install dependencies
        run: make install
      - name: Update .kolmafia-revision
        run: echo -n "${{ env.revision_number }}" > .kolmafia-revision
      - name: Update library.py
        run: uv run python scripts/generate_library.py
      - name: Format
        run: make format
        continue-on-error: true
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update KoLmafia to r${{ env.revision_number }}"
