name: Update KoLmafia
on:
  workflow_dispatch:
    inputs:
      revision:
        description: "KoLmafia revision"
        default: "latest"
        type: string
jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      desired-revision: ${{ env.desired_revision }}
      current-revision: ${{ env.current_revision }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get current revision
        run: echo "current-revision=$(cat .kolmafia-revision)" >> $GITHUB_ENV
      - name: Determine desired revision
        run: |
          echo "desired-revision=$(
            if [[ ${{ github.event.inputs.revision }} == "latest" ]]; then
              curl https://api.github.com/repos/kolmafia/kolmafia/releases/latest -s | jq .name -r
            else
              echo ${{ github.event.inputs.revision }}
            fi
          )" >> $GITHUB_ENV
      - name: Validate desired revision
        if: env.desired-revision <env.current-revision
        uses: actions/github-script@v7
        with:
          script: core.setFailed('cannot downgrade KoLmafia versions')
  update:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.desired-revision > needs.validate.outputs.current-revision
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin
      - name: Update .kolmafia-revision
        run: echo -n "${{ env.revision_number }}" > .kolmafia-revision
      - name: Update ash/library.py
        run: uv run python scripts/generate_ash_library.py
      - name: Format
        run: make format
        continue-on-error: true
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update KoLmafia to r${{ env.revision_number }}"
